name = "Venture"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32f47a975ef8216d231a46decf58b618263667f424ab8bf19c93484e4fe9eec3"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources"
