name = "Venture"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f26062f4af3911f38b02e2608dc663a20e28be063fc928a76144a35f0d3e31d"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources"
