name = "Venture"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e805f9a3e207f307f292432ce82ef0fd2615728efad20bcf27e577589bfe7830"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources"
